name: xenon
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_blue: ^0.8.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7
  page_transition: ^2.0.5
  flutter_mobx: ^2.0.6+4
  ionicons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter-regular.otf
        - asset: fonts/inter-bold.otf
          weight: 700